# Generated by Django 4.2.23 on 2025-08-02 00:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="reason_disease",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="reason_goal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="reason_macro",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailyhistory",
            name="score_disease",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dailyhistory",
            name="score_goal",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dailyhistory",
            name="score_macro",
            field=models.IntegerField(),
        ),
    ]
