# Generated by Django 4.2.23 on 2025-08-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyhistory",
            name="advice_disease",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="advice_goal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="advice_macro",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="diet_goal",
            field=models.CharField(default="maintain", max_length=20),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="gender",
            field=models.CharField(default="M", max_length=1),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_anemia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_constipation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_diabetes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_fatty_liver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_gastritis_or_ulcer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_gout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_hyperhomocysteinemia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_hyperlipidemia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_hypertension",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_ibs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_metabolic_syndrome",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="has_obesity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dailyhistory",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
